import clsx from "clsx";
import { Inter } from "next/font/google";

import "./layout.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={clsx(inter.variable)} lang="en">
      <body>{children}</body>
    </html>
  );
}
